FROM tensorflow/tensorflow:latest-py3-jupyter

RUN apt-get -y install python-opencv
RUN pip3 --no-cache-dir install opencv-python
RUN pip3 --no-cache-dir install sklearn
RUN pip3 --no-cache-dir install keras
